on: push
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config user.name  "thaim"
          git config user.email "thaim@example.com"
          git add .
          git commit -m "generated"
          git push